Repository Team-TTT/Circle-Web-FE, pull requests merged in 2022-10, with the labels that each got.

#1 docs: pr 관련 파일 생성
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: docs, review-required

#2 feat: react 초기 시작 셋팅
  .eslintignore
  .eslintrc.js
  .gitignore
  .husky/pre-commit
  App.js
  README.md
  index.js
  package-lock.json
  package.json
  prettier.config.js
  public/index.html
  src/App.js
  src/index.js
Labels: review-required, feat

#4 feat: 홈페이지 UI 구현 완료
  App.js
  index.js
  package-lock.json
  package.json
  src/App.js
  src/GlobalStyle.js
  src/app/App.js
  src/assets/app1.png
  src/assets/app2.png
  src/assets/app3.png
  src/components/common/.gitkeep
  src/config/constants/theme.js
  src/index.js
  src/layout/ConsoleLayOut/index.js
  src/layout/HomeLayOut/Navbar.js
  src/layout/HomeLayOut/index.js
  src/pages/ChannelDetailPage/index.js
  src/pages/ChannelsPage/index.js
  src/pages/ErrorPage/index.js
  src/pages/GuidePage/index.js
  src/pages/HomePage/index.js
  src/pages/NotFoundPage/index.js
  src/pages/ProjectDetailPage/index.js
  src/pages/ProjectsPage/index.js
Labels: review-required, feat

#5 feat: guide 페이지 레이아웃
  package-lock.json
  src/pages/GuidePage/index.js
Labels: review-required, feat

#6 feat: 모달창 구현
  package-lock.json
  package.json
  public/index.html
  src/components/common/.gitkeep
  src/components/common/Modal/Portal.js
  src/components/common/Modal/index.js
  src/config/constants/theme.js
  src/hooks/useModal.js
Labels: review-required, feat

#7 [2022.10.19] feat: sidebar
  public/index.html
  src/app/App.js
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/fonts.js
  src/assets/images/app1.png
  src/assets/images/app2.png
  src/assets/images/app3.png
  src/components/common/Modal/index.js
  src/index.js
  src/layout/ConsoleLayOut/Sidebar.js
  src/layout/ConsoleLayOut/index.js
  src/pages/HomePage/index.js
Labels: review-required, feat

#8 [2022.10.19] feat: firebase auth를 사용한 로그인 구현
  env.sample
  package-lock.json
  package.json
  src/api/authApi.js
  src/app/App.js
  src/config/firebaseConfig.js
  src/config/index.js
  src/hooks/useLogin.js
  src/hooks/useLogout.js
  src/layout/ConsoleLayOut/Sidebar.js
  src/layout/HomeLayOut/Navbar.js
  src/pages/ProtectedRoute/index.js
Labels: review-required, feat

#9 [2022.10.21] feat: 토스트 컴포넌트 구현
  .eslintrc.js
  package-lock.json
  package.json
  public/index.html
  src/components/common/Modal/Portal.js
  src/components/common/Modal/index.js
  src/components/common/Portal/index.js
  src/components/common/ToastMessage/index.js
  src/config/constants/index.js
  src/hooks/useToast.js
Labels: review-required, feat

#10 [2022.10.22] feat: error page 구현
  .github/pull_request_template.md
  package.json
  src/pages/ErrorPage/index.js
  src/pages/NotFoundPage/index.js
Labels: review-required, feat

#11 [2022.10.25] feat: 콘솔 버튼 설치 및 설정 페이지 구현
  package.json
  src/api/projectApi.js
  src/app/App.js
  src/components/common/ToastMessage/index.js
  src/components/project/ProjectForm.js
  src/components/project/ProjectHeader.js
  src/components/project/ProjectHeaderDropdown.js
  src/config/constants/index.js
  src/hooks/useLogin.js
  src/layout/ConsoleLayOut/Sidebar.js
  src/layout/ConsoleLayOut/index.js
  src/pages/HomePage/index.js
  src/pages/ProjectDetailPage/index.js
  src/pages/ProjectsPage/index.js
  src/pages/ProtectedRoute/index.js
  src/utils/checkSessionCookie.js
Labels: review-required, feat

#12 [2022.10.26] feat: 채널페이지 구성 완료
  .env.sample
  package-lock.json
  package.json
  src/api/channelApi.js
  src/app/App.js
  src/components/channel/ChannelCreate.js
  src/components/channel/ChannelDelete.js
  src/components/channel/ChannelEdit.js
  src/components/channel/ChannelForm.js
  src/components/channel/CustomInput.js
  src/components/common/Modal/index.js
  src/components/project/ProjectForm.js
  src/components/shared/CustomButton.js
  src/components/shared/StyledButton.js
  src/components/shared/StyledInput.js
  src/config/constants/index.js
  src/hooks/useChange.js
  src/hooks/useChannelForm.js
  src/hooks/useModal.js
  src/layout/ConsoleLayOut/Sidebar.js
  src/pages/ChannelDetailPage/index.js
  src/pages/ChannelsPage/index.js
Labels: review-required, feat

#14 [2022.10.27] refactor: 토스트 컴포넌트 사용성 개선 및 콘솔페이지 UX 개선을 위한 리팩토링
  package.json
  src/app/App.js
  src/components/channel/CustomInput.js
  src/components/common/ToastMessage/index.js
  src/components/project/ProjectForm.js
  src/components/project/ProjectHeader.js
  src/components/project/ProjectHeaderDropdown.js
  src/components/shared/DownIcon.js
  src/components/shared/StyledButton.js
  src/config/constants/index.js
  src/hooks/useLogin.js
  src/hooks/useToast.js
  src/layout/ConsoleLayOut/Sidebar.js
  src/layout/ConsoleLayOut/index.js
  src/pages/ChannelsPage/index.js
  src/pages/HomePage/index.js
  src/pages/NewProjectPage/index.js
  src/pages/ProjectDetailPage/index.js
  src/pages/ProjectsPage/index.js
Labels: review-required, refactor

#15 feat: 채널페이지 CRUD 완료시 토스트컴포넌트로 알림메세지 기능 추가
  src/config/constants/index.js
  src/pages/ChannelsPage/index.js
Labels: review-required, feat

#16 feat: 코드스니펫 추가
  package-lock.json
  package.json
  src/pages/ChannelsPage/index.js
  src/pages/ProjectDetailPage/index.js
Labels: review-required, feat, refactor

#17 test: 채널 및 프로젝트 기본적인 테스트코드 작성
  .eslintignore
  src/api/authApi.js
  src/components/channel/ChannelForm.js
  src/components/common/Modal/index.js
  src/components/project/ProjectHeader.js
  src/hooks/useLogin.js
  src/pages/ChannelsPage/index.js
  src/pages/ProjectDetailPage/index.js
  src/setupTests.js
  src/spec/ChannelsPage.spec.js
  src/spec/ProjectDetailPage.spec.js
Labels: review-required, test
