Repository Team-TTT/Circle-Web-FE, pull requests merged in 2022-11, with the labels that each got.

#21 test: 프로젝트 페이지 CRUD 테스트 코드 추가
  src/components/project/ProjectForm.js
  src/components/project/ProjectHeader.js
  src/spec/ProjectDetailPage.spec.js
Labels: review-required, test

#18 [2022.10.31] refactor: 홈화면에서 쿠키를 기반으로 경로를 분기처리하던 동작 삭제
  package-lock.json
  package.json
  src/components/common/ToastMessage/index.js
  src/components/project/ProjectForm.js
  src/components/project/ProjectHeader.js
  src/config/constants/index.js
  src/layout/ConsoleLayOut/index.js
  src/pages/HomePage/index.js
  src/pages/ProjectDetailPage/index.js
  src/pages/ProjectsPage/index.js
  src/utils/checkSessionCookie.js
Labels: review-required, refactor

#19 [2022.10.31] feat: guide page content
  src/pages/GuidePage/MarkdownRenderer.js
  src/pages/GuidePage/index.js
  src/pages/ProjectDetailPage/index.js
Labels: review-required, feat

#20 [2022.11.01] test: 토스트 컴포넌트 유닛테스트 작성
  src/layout/ConsoleLayOut/index.js
  src/spec/components/ToastMessage.spec.js
Labels: review-required, test

#22 docs: readme.md 추가
  README.md
  package-lock.json
Labels: docs, review-required
